### ISSUE TITLE
blocked from freeCodeCamp

### ISSUE THREAD

**Issue by aeveritt84** [raisedadead/ama#10]
Hi,

I'm sorry I'm new to Github, I'm not sure why I was blocked, or what I did wrong. Any insight would be helpful.

Thank you

**Comment by raisedadead** [comment]
Hi,

Thanks for reaching out.

We found you were creating invalid, low effort and unwanted pull-requests.

Each pull-request uses resources like Travis CI, and other things which we being an Open Source non-profit have limitations on.

This is against our https://www.freecodecamp.org/news/code-of-conduct, We strictly enforce our Code of Conduct.

We understand your interest in contributing, but you should first read our Code of Conduct linked above and then follow the [guidelines for contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md)

We will remove the block on your user account once you confirm that you agree to this.

Thanks.

**Comment by aeveritt84** [comment]
I apologize and agree. Thank you for taking the time to reply back

**Comment by raisedadead** [comment]
Thanks a lot, for confirming. I have unblocked you from the organisation. Please give our contributing guide a read. I am pretty sure, you could help in a lot of meaningful ways.

You can reach us in [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) should you have any questions.
