### ISSUE TITLE
scope of web development in india

### ISSUE THREAD

**Issue by arrbxr** [raisedadead/ama#6]
hello sir,
    I'm abhishek raj ravi from bihar.
    please tell me scope of web development in india.
    tahnk you.

**Comment by raisedadead** [comment]
Hi Abhishek,

Thanks for taking the time, to reach out. However its a very broad question, and I am totally not an expert on such opinion based questions. I would recommend you to take a look at what others have answered.

https://www.quora.com/search?q=Scope+of+web+development+in+india

Goodluck.
