### ISSUE TITLE
About freeCodeCamp's event repository. 

### ISSUE THREAD

**Issue by chaitanyagiri** [raisedadead/ama#7]
The project looks interesting can you give me some headers how can I start contributing to it as nothing is really defined clearly(probably because it's just started)?

**Comment by raisedadead** [comment]
Yes, you are correct this project just got started and currently its very very early to give you any guidelines on contributing to this repo.

You should follow the repo (by starring it). We will have some announcements as soon as its in a shape for contributions. And trust me we need all the help we can.

Psst. [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) is where we hang out!
