### ISSUE TITLE
What is the nature of work you do everyday?

### ISSUE THREAD

**Issue by dhananzen** [raisedadead/ama#9]
How does your working day look like?
Do you work remote?

**Comment by raisedadead** [comment]
Thanks for reaching out to me.

> How does your working day look like?

I usually tend to maximize my overlap with our team mates in the US, although we have people working all across the  world. I start at around noon and end up working till late in the evening.

I get all my emails and chats and notifications addressed by the first two hours of the day. Then on there are regular dev and devops stuff to be managed. Most of my work revolves around getting caught up with the community, and especially with out long term volunteer contributors.

Meetings and calls are usually for the evening. Although I am very flexible usually.

> Do you work remote?

Our entire team is 100% remote. We try and meet a couple times a year in person, when possible.

**Comment by dhananzen** [comment]
Cool, thanks!
Good to know a fellow Punekar who is contributing to great things ✨
